-- !Ups
CREATE TABLE "HABITS" (
  "ID" UUID NOT NULL PRIMARY KEY,
  "NAME" VARCHAR(255),
  "GOAL" VARCHAR(255)
);

CREATE TABLE "HABIT_HISTORY"(
  "ID_HABIT" UUID REFERENCES "HABITS"("ID") ON DELETE CASCADE,
  "IS_DONE" BOOLEAN,
  "DATE" DATE
);
-- !Downs
DROP TABLE "HABIT_HISTORY";
DROP TABLE "HABITS";
